### ISSUE TITLE
How i can use this repo to create a blog?

### ISSUE THREAD

**Issue by Alias851** [NamPNQ/farmville2linkexchange#1]
I want only to know how can i use this repo to create a blog for farmville 2.

**Comment by NamPNQ** [comment]
ok, np

2014-11-03 2:39 GMT+07:00 Alias851 notifications@github.com:

> I want only to know how can i create this repo to create a blog for
> farmville 2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NamPNQ/farmville2linkexchange/issues/1.

## 

[image: photo]
_Phạm Ngọc Quang Nam_
Developer
m:0169.22.23.24.9 | e:nampnq@gmail.com | w:http://nampnq.vietnamcode.info
https://www.facebook.com/nampnq  http://www.linkedin.com/in/nampnq
https://twitter.com/nampnq  https://plus.google.com/+NamPhamNgocQuang/

**Comment by Alias851** [comment]
Yes tnks, but how?

**Comment by NamPNQ** [comment]
First read: https://cloud.google.com/appengine/docs/python/gettingstartedpython27/uploading

**Comment by Alias851** [comment]
Ok tnks tomorrow i will do and let you know. Again tnks :)

**Comment by Alias851** [comment]
I ve done all and replace your file repo in google app engine launcher but the result is this http://fv2linkexchange.appspot.com/

**Comment by Alias851** [comment]
please can u help me?

**Comment by NamPNQ** [comment]
lol, deploy my source, not deploy hello world

2014-11-06 2:05 GMT+07:00 Alias851 notifications@github.com:

> please can u help me?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NamPNQ/farmville2linkexchange/issues/1#issuecomment-61862630
> .

## 

[image: photo]
_Phạm Ngọc Quang Nam_
Developer
m:0169.22.23.24.9 | e:nampnq@gmail.com | w:http://nampnq.vietnamcode.info
https://www.facebook.com/nampnq  http://www.linkedin.com/in/nampnq
https://twitter.com/nampnq  https://plus.google.com/+NamPhamNgocQuang/

**Comment by Alias851** [comment]
I replaced with your repo, i will try again. Tnks.

**Comment by Alias851** [comment]
i tried but do u have a video or an explanation because i don't manage to. Obviously i will send u a Donation :)

**Comment by NamPNQ** [comment]
Step 1.

```
git clone https://github.com/NamPNQ/farmville2linkexchange
```

Step 2. Open file app.yaml, change application from `namphamngocquang` to `fv2linkexchange`
Step 3. 

```
appcfg.py update .
```

**Comment by Alias851** [comment]
For updating i have to write this code: appcfg.py update app.yaml otherwise with farmville2linkexchange doesn't work: Directory does not contain an famrville2linkexchange.yaml configuration file.
Anyway i update with app.yaml but always Hello World.

**Comment by NamPNQ** [comment]
You can send teamviewer id for me, i free in today from 12h00->13h00 GMT +7 via
skype: nampnq or telegram: 841692223249

**Comment by Alias851** [comment]
ok Added on Skype
